### ISSUE TITLE
Database vs Scavager PSM list for filtering

### ISSUE THREAD

**Issue by ashwinkallor** [markmipt/scavager#1]
Hi, I have a question regarding using a database in Scavager or not. (I am using Scavager 0.2.4). I have used Scavager both with and without a database to filter peptides at 1% FDR. When I filter using a database (containing decoys), I seem to be getting more results at PSM, protein & protein group levels.  However, when I do not use a database but filter only using PSM list provided by Scavager, I get less results. I just wanted to know which of these methods is the recommended one? And why is there such a difference between the number of PSMs obtained? (For instance, when I use a database, I get ~2500 PSMs and without, ~350 PSMs). I am searching against mouse data.

**Comment by markmipt** [comment]
Hi!

That is really strange. The database usage should only result in additional output  columns such as protein sequence coverage and LFQ quantitation. I've checked it right now (with fresh install of version 0.2.4) and I got almost the same number of identifications with/without using of db (small fluctuation is ok due to random seeds inside the code).

Could you please share your search and fasta files with me?

Regards,
Mark
